openapi: 3.0.0
info:
  version: 1.0.0
  title: Ecommerce API
  description: APIs para la aplicación de ecommerce
paths:
  /api/products:
    get:
      summary: Obtener una lista de productos
      responses:
        200:
          description: Una lista de productos.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      security:
        - bearerAuth: []
      summary: Crear un producto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: El producto creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /api/products/{pid}:
    get:
      summary: Obtener un producto por su ID
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
      responses:
        200:
          description: El producto.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Producto no encontrado.
    put:
      security:
        - bearerAuth: []
      summary: Actualizar un producto
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: El producto actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Producto no encontrado.
    delete:
      security:
        - bearerAuth: []
      summary: Eliminar un producto
      parameters:
        - in: path
          name: pid
          required: true
          schema:
            type: string
      responses:
        200:
          description: Producto eliminado.
        404:
          description: Producto no encontrado.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Product:
      type: object
      required:
        - title
        - description
        - code
        - price
        - status
        - stock
        - category
        - thumbnails
      properties:
        title:
          type: string
        description:
          type: string
        code:
          type: string
        price:
          type: number
        status:
          type: boolean
        stock:
          type: number
        category:
          type: string
        thumbnails:
          type: array
          items:
            type: string
        owner:
          type: string
      example:
        title: Producto 1
        description: Este es el producto 1
        code: P1355
        price: 100
        status: true
        stock: 50
        category: Libros
        thumbnails: ["http://example.com/image1.jpg"]
        owner: prueba@gmail.com